source "https://rubygems.org"

gem "pg", "~> 0.21"
gem "puma", "~> 3.8"
gem "rails", "~> 5.1"
gem "rake", "~> 12.0"
gem "slim-rails", "~> 3.1"
gem "webpacker", "~> 1.2"

group :development, :test do
  gem "awesome_print", "~> 1.8"
  gem "bond", "~> 0.5"
  gem "dotenv-rails", "~> 2.2"
  gem "git-cop", "~> 1.6"
  gem "hirb", "~> 0.7"
  gem "pry", "~> 0.10"
  gem "pry-byebug", "~> 3.4"
  gem "pry-state", "~> 0.1"
  gem "rails_best_practices", "~> 1.18", require: false
  gem "reek", "~> 4.7", require: false
  gem "rspec-rails", "~> 3.6"
  gem "rubocop", "~> 0.49", require: false
  gem "scss_lint", "~> 0.51", require: false
  gem "wirb", "~> 2.1"
end

group :development do
  gem "listen", "~> 3.1"
  gem "milestoner", "~> 6.2", require: false
  gem "pragmater", "~> 4.2", require: false
  gem "tocer", "~> 6.2", require: false
end

group :test do
  gem "capybara", "~> 2.14"
  gem "climate_control", "~> 0.1"
  gem "codeclimate-test-reporter", "~> 1.0"
  gem "factory_girl_rails", "~> 4.8"
  gem "launchy", "~> 2.4"
  gem "vcr", "~> 3.0"
end
