source "https://rubygems.org"

# Databases
gem "sqlite3"

# Application
gem "rake"
gem "rails", "4.1.0"

# Assets
gem "uglifier"
gem "sass-rails"
gem "bower-rails"

group :development, :test do
  gem "dotenv-rails"
end

group :test do
  gem "rspec-rails"
end
