source "https://rubygems.org"

# Databases
gem "sqlite3"

# Server
gem "puma"

# Application
gem "rake"
gem "rails", "~> 4.2"

# Assets
gem "uglifier"
gem "slim-rails"
gem "sass-rails"
gem "jquery-rails"

group :development, :test do
  gem "dotenv-rails"
  gem "pry"
  gem "pry-byebug"
  gem "pry-state"
  gem "bond"
  gem "wirb"
  gem "hirb"
  gem "awesome_print"
  gem "rspec-rails", "~> 3.3"
  gem "jasmine"
  gem "jasmine-jquery-rails"
  gem "rubocop", require: false
  gem "rails_best_practices", require: false
  gem "scss_lint", require: false
end

group :development do
  gem "pragmater"
  gem "tocer"
  gem "milestoner"
end

group :test do
  gem "factory_girl_rails"
  gem "climate_control"
  gem "vcr"
  gem "capybara"
  gem "launchy" # Allows save_and_open_page to work in Capybara.
  gem "poltergeist"
  gem "codeclimate-test-reporter", require: false
end
