require_relative "config/application"

begin
  require "reek/rake/task"
  require "rubocop/rake_task"
  require "scss_lint/rake_task"

  Reek::Rake::Task.new
  RuboCop::RakeTask.new
  SCSSLint::RakeTask.new { |task| task.files = ["app/assets"] }
rescue LoadError => error
  puts error.message
end

Rails.application.load_tasks

desc "Run Rails Best Practices"
task :rails_best_practices do
  puts "Running Rails Best Practices..."
  fail unless system "rails_best_practices --silent"
end

task(:default).clear
task default: %w[spec reek rubocop rails_best_practices scss_lint]
